### ISSUE TITLE
load_mbb_player_box(2023) not working

### ISSUE THREAD

**Issue by SahilTilak** [sportsdataverse/hoopR#113]
load_mbb_player_box(2023) returns team data instead of player data. The function works for all years before 2023, though.

**Comment by saiemgilani** [comment]
What version of hoopR are you using?

First, restart your R session, then try:
```r
remotes::install_github("sportsdataverse/hoopR")
```
Then restart your R session again, then retry your query.

**Comment by SahilTilak** [comment]
Yes, it works now. Thank you!
