### ISSUE TITLE
most_recent_nba_season()  (2024) not found

### ISSUE THREAD

**Issue by Coop197823** [sportsdataverse/hoopR#128]
code: `hoopR::most_recent_nba_season() ` - returns 2024

when then running code:
`mbb_team_schedule <- hoopR::load_nba_schedule(seasons = most_recent_nba_season())
`
an error retruns:

Warning messages:
1: In readRDS(con) :
  cannot open URL 'https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_nba_schedules/nba_schedule_2024.rds': HTTP status was '404 Not Found'
2: Failed to readRDS from <https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_nba_schedules/nba_schedule_2024.rds>

when going to the site: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_nba_schedules
It seems that ESPN does not have a 2024 season schedule.  Do you know if this is something that will be updated and if so when?

**Comment by bzigterman** [comment]
Similar issue when running `most_recent_nba_season())`:

```
> load_nba_team_box(seasons = most_recent_nba_season())
─────────────────────────────────────────────────────────────────────────────── hoopR 1.8.0 ──
# A tibble: 0 × 0
Warning messages:
1: In readRDS(con) :
  cannot open URL 'https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/nba/team_box/rds/team_box_2024.rds': HTTP status was '404 Not Found'
2: Failed to readRDS from <https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/nba/team_box/rds/team_box_2024.rds> 
```

**Comment by saiemgilani** [comment]
I hear you fellas, I'm busy rn with professional NBA work. I will try to get to updating the data repositories for 2024

**Comment by Coop197823** [comment]
No worries mate, I appreciate the update.  Look forward to your work, it is much appreciated.

**Comment by saiemgilani** [comment]
Try now and if you're still having issues, please make sure to update your package with:

```r
remotes::install_github('sportsdataverse/hoopR')
```
then refresh your R session and check again. If issues persist from that point, please holler

**Comment by Coop197823** [comment]
working as intended now, ty!
