### ISSUE TITLE
hoopR::load_mbb_schedule(2024:2024) resturning zero records

### ISSUE THREAD

**Issue by Coop197823** [sportsdataverse/hoopR#131]
I assume this is similar to the issue I reported a few weeks back with the NBA, but the latest 2023/2024 season is coming up with zero records when I run:

`hoopR::load_mbb_schedule(2024:2024)`

It does return all the records if I run the 2023 season.

I did update the package again.  Again, I appreciate your efforts here!

**Comment by Coop197823** [comment]
Just following up here to see if a solution will be presented?

**Comment by aggieed97** [comment]
Having the same issue (hoopR 2.0.1 in use).

Assuming that the file for the MBB Schedules is from the following link:

https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_mens_college_basketball_schedules

Which shows that 2024 data has not been uploaded yet.

**Comment by Coop197823** [comment]
Any Update on this?  I still do not see the mbb_schedule_2024.rds at the above link

**Comment by aqsmith08** [comment]
Will this bug resolve the same error when I run something like

`foo <- hoopR::load_mbb_player_box(seasons = 2024)`

Or do I need to submit a standalone issue for that? Thanks and very much appreciate your work on this package! :pray:

**Comment by Coop197823** [comment]
It should, but the developer seems to not want to keep this project going.

**Comment by Coop197823** [comment]
yes, the same issue happened with the NBA data at the beginning of this season.  The developer had been busy with his day job and hopped on and had the webscrape fixed within a day or two of the season start.  It seems it he taken him a bit longer to get to for College Bball.

**Comment by saiemgilani** [comment]
I agree and all that, your summarization of the situation is accurate, I'd say. The start of the NBA season has had me busier than usual. While I apologize for the delay and general lack of transparency due to the lack of communication, I will get on it for both MBB/WBB and pushing updates to CRAN

**Comment by aqsmith08** [comment]
`hoopR::load_mbb_schedule(2024)` and `foo <- hoopR::load_mbb_player_box(seasons = 2024)` loads the appropriate data now. I think that this issue may be marked as fixed. Thanks so much for your work on this!

**Comment by Coop197823** [comment]
Everything is working as intended, you can consider this closed.  I would also be interested in helping with getting the API up and running for the NBA and NCAA basketball seasons next year if you need a helping hand.
