### ISSUE TITLE
kp_team_players does not return data for 2024.

### ISSUE THREAD

**Issue by aaronmorrisNC** [sportsdataverse/hoopR#133]
I have a valid subscription to KenPom and try(kp_team_players(team = 'Utah', year = 2024)) is not returning data for 2024.  It works for 2023 and earlier but not 2024.

![Screenshot 2023-11-27 162844](https://github.com/sportsdataverse/hoopR/assets/112770416/4e7d7f7e-ef77-4548-8ada-932e769d6500)

I can confirm that the KenPom website does have 2024 player data.

![ken](https://github.com/sportsdataverse/hoopR/assets/112770416/4c19aff0-4dd0-4299-965a-8955bba7cf1c)

I am using R Studio 2023.06.1 Build 524

**Comment by saiemgilani** [comment]
```r
remotes::install_github("sportsdataverse/hoopR")
```

And try again. I forgot to update a critical internal dataset causing the issue in the most recent CRAN release and will rectify this asap

**Comment by aaronmorrisNC** [comment]
I ran

remotes::install_github("sportsdataverse/hoopR")

but now getting a slightly different error

![image](https://github.com/sportsdataverse/hoopR/assets/112770416/50037ef7-9b1c-4fa1-8ded-edffa6be20aa)

**Comment by saiemgilani** [comment]
I get something like this:

![image](https://github.com/sportsdataverse/hoopR/assets/25425933/2b737d4c-2167-41ae-aedf-3eef5bfe2e74)

It's kind of a bad error message, it thinks there should be a second set of data for conference only data

**Comment by aaronmorrisNC** [comment]
Although I get an error, the data is being retrieved.

![image](https://github.com/sportsdataverse/hoopR/assets/112770416/9dac621f-827d-48df-876d-c0fcc197248c)

**Comment by saiemgilani** [comment]
I'm closing this then, appreciated.
