### ISSUE TITLE
load_nba_team_box() , schedule and pbp are missing 14th of march games

### ISSUE THREAD

**Issue by RikiBriki** [sportsdataverse/hoopR#145]
For some reason, 14th of march is missing,  ( yesterday at the time i am writing this post)

**Comment by RikiBriki** [comment]
Seems like it's possible to manually update with scrapers in case i want faster updates, issue can be closed. It could be a fun and productive task to make something thats the most up to date live data source, might look into it

**Comment by saiemgilani** [comment]
> Seems like it's possible to manually update with scrapers in case i want faster updates, issue can be closed. It could be a fun and productive task to make something thats the most up to date live data source, might look into it

yep
