### ISSUE TITLE
Support for NCAA Women's basketball / WNBA?

### ISSUE THREAD

**Issue by markjrieke** [sportsdataverse/hoopR#149]
Right now, the package only supports men's NCAA / NBA --- can you roadmap adding support for NCAA women's basketball / WNBA?

**Comment by billyfryer** [comment]
Hello!

WNBA and NCAA Women’s Basketball data is in the wehoop package linked below:

https://wehoop.sportsdataverse.org/

The men’s and women’s data is separated so as not to make the package size too large.

Thanks,
Billy Fryer

**Comment by markjrieke** [comment]
ah, perfect, thank you!
