### ISSUE TITLE
Inconsistency in Game Spreads

### ISSUE THREAD

**Issue by abodesy14** [sportsdataverse/hoopR#47]
Hi there - I have noticed there are some inconsistencies with the game spreads.

Here is an example: 

In the first 3 rows, powerhouses like Gonzaga, Kansas, and Baylor are the home team and heavily favored. The home_team_spread column is **negative**.

In rows 4-6, Michigan, Duke, and Illinois are the home team and heavy favorites, but this time the home_team_spread column is **positive**.

All the home teams in this subset were favored but are being labeled differently in the spread columns. 

![image](https://user-images.githubusercontent.com/46985185/143136468-6f67311c-21e0-4377-9eca-afaaf4a23143.png)

Is there an easy fix for this?

**Comment by saiemgilani** [comment]
Good issue, will look into it
