### ISSUE TITLE
Trouble loading KenPom player page

### ISSUE THREAD

**Issue by gitmoneyMSBA** [sportsdataverse/hoopR#74]
I get the following error running `kp_team_players(tm_name, year = season)`:

Error in kp_team_players(tm_name, year = season) : 
  object 'kenpom' not found

Digging in a little further, it looks like when I try to pull roster pages, I get the following:

Warning message:
In session_set_response(x, resp) : Too Many Requests (RFC 6585) (HTTP 429).

**Comment by saiemgilani** [comment]
You are making too many requests, I would suggest slowing down on the speed of your calls with a rest (i.e. Sys.sleep() of some kind) between calls. This feels like it is a problem that the package should not inherently need to solve if you follow polite scraping.
