### ISSUE TITLE
espn_nba_teams function error

### ISSUE THREAD

**Issue by schmid07** [sportsdataverse/hoopR#81]
**Describe the bug**
Using version 1.5.0 of hoopR, running espn_nba_teams() function in RStudio, I get following error msg: 

2022-05-21 17:35:04: Invalid arguments or no teams data available!
Error in espn_nba_teams() : object 'teams' not found

**To Reproduce**
See above.

**Expected behavior**
See above.

**Screenshots**
See above.

**Desktop (please complete the following information):**
error on windows and mac

**Smartphone (please complete the following information):**
na

**Additional context**
Great package and appreciate any feedback.

**Comment by saiemgilani** [comment]
This is fixed in the dev version of the pkg on GitHub
