### ISSUE TITLE
Home and Away are wrong

### ISSUE THREAD

**Issue by grayskripko** [sportsdataverse/hoopR#91]
I've checked 20 matches from https://www.espn.com/nba/game/_/gameId/401071880 till https://www.espn.com/nba/game/_/gameId/401071899. All of them confuse the sides Home and Away. 
I extrapolate this observation on all games. 
Please, switch them.

**Comment by saiemgilani** [comment]
yeah mane, it's being fixed. I just need to rescrape. A good amount of data is in this state, apologies

**Comment by saiemgilani** [comment]
related #47

**Comment by aaronmorrisNC** [comment]
My apologies if I am going about this the wrong way but any updates with the H/A being reversed?

**Comment by saiemgilani** [comment]
I think I have now fixed this from the data repo side and if you update to the github version (soon to be pushed to CRAN), you should hopefully not encounter any issues

**Comment by saiemgilani** [comment]
Update: nope, will fix tn

**Comment by aaronmorrisNC** [comment]
Good evening @saiemgilani, any idea when this will be resolved?

**Comment by saiemgilani** [comment]
I believe this issue should now be resolved, please open another issue if this is not the case so I can reexamine
