### ISSUE TITLE
Object 'kenpom' not found

### ISSUE THREAD

**Issue by sawyerjjohnson** [sportsdataverse/hoopR#93]
I have a KenPom account and I have followed the instructions for how to login via R, It even recognizes that I do have an account. However, when I try to load any of the KenPom packages I get an error along the lines of:

"object 'kenpom' not found"

Is there a reason why I can't load any of the KenPom information?

**Comment by saiemgilani** [comment]
Please try with development version 1.8.1 and please report back on the status. Appreciate the note!
```
# You can install using the pacman package using the following code:
if (!requireNamespace('pacman', quietly = TRUE)){
  install.packages('pacman')
}
pacman::p_load_current_gh("sportsdataverse/hoopR", dependencies = TRUE, update = TRUE)
```

**Comment by sawyerjjohnson** [comment]
This seemed to work. Thank you very much for your help!
