### ISSUE TITLE
Unable to access KenPom data in R

### ISSUE THREAD

**Issue by Harrisoneller** [sportsdataverse/hoopR#99]
**Describe the bug**
When using 'login' function, it returns:

Error in read_html.response(x$response, ..., base_url = x$url) : 
  Forbidden (HTTP 403).
In addition: Warning message:
In session_set_response(x, resp) : Forbidden (HTTP 403).

**To Reproduce**
1. Go to R
2. load hoopR
3. try 'login' function with Kenpom credential 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 
- R version:  4.2.2

**Comment by saiemgilani** [comment]
what version of hoopR are you using? Once you set the `KP_USER` and `KP_PW` environment variables and refresh your session, you should not need need any direction interaction with the login function.  Please see for reference on how the login function is used:
https://hoopr.sportsdataverse.org/reference/kp_user_pw.html

**Comment by aaronmorrisNC** [comment]
I am getting the same error when calling the following function:

login(user_email = Sys.getenv("KP_USER"), user_pw = Sys.getenv("KP_PW"))

Error returned:

Error in read_html.response(x$response, ..., base_url = x$url) : 
  Forbidden (HTTP 403).
In addition: Warning message:
In session_set_response(x, resp) : Forbidden (HTTP 403).

**Comment by aaronmorrisNC** [comment]
Is it possible that I am being flagged as a bot and my authentication denied?

**Comment by Deschaine17** [comment]
I got the same error as aaronmorrisNC

**Comment by saiemgilani** [comment]
If you're still having issues, please make sure to update your package with:

```r
remotes::install_github('sportsdataverse/hoopR')
```
then refresh your R session and check again. If issues persist from that point, please holler
